eureka:
  client:
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      zone: BakerLocalZone