spring:
  application:
    name: Baker-Register-Service

server:
  port: 8763
  
eureka:
  instance:
    hostname: 192.169.1.104
  client:
    serviceUrl:
      defaultZone: http://192.169.1.106:8762/eureka/               