spring:
  application:
    name: Baker-Register-Service

server:
  port: 8763
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:876/eureka/               