spring:
  application:
    name: Baker-Register-Service

server:
  port: 8762
  
eureka:
  instance:
    hostname: 192.169.1.106
  client:
    serviceUrl:
      defaultZone: http://192.169.1.104:8763/eureka/