spring:
  application:
    name: Baker-Register-Service

---

server:
  port: 8761
spring:
  profiles: local
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---

server:
  port: 8762
spring:
  profiles: local2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      
---

server:
  port:8763
spring:
  profiles: local3
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/                 