spring:
  application:
    name: Baker-Register-Service

server:
  port: 8763
  
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/               