spring:
  application:
    name: Baker-Register-Service

server:
  port: 8762
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/               