eureka:
  client:
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    instance:
      metadataMap:
        zone: baker
