server:
  port: 8080
  
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andy-Shao/GearEE-Baker
          searchPaths: Default/conf/dev
